development:
  adapter: postgresql
  encoding: utf8
  database: ivona_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: ivona_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: ivona_production
  pool: 5
  username:
  password:
